// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPosition(arg1:number):Promise<number>;

export function IsPlaying(arg1:number):Promise<boolean>;

export function LoadTrack(arg1:number,arg2:string):Promise<main.TrackMetadata>;

export function Pause(arg1:number):Promise<void>;

export function Play(arg1:number):Promise<void>;

export function Seek(arg1:number,arg2:number):Promise<void>;

export function SelectAudioFile():Promise<string>;

export function SetPitch(arg1:number,arg2:number):Promise<void>;

export function SetTempo(arg1:number,arg2:number):Promise<void>;

export function SetVolume(arg1:number,arg2:number):Promise<void>;

export function ToggleAutoMix(arg1:boolean):Promise<void>;
